name: .NET Framework CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0


      - name: Build application
        run: msbuild ./Kiandra_FA2_SLD521_ComicBookStore.sln /p:Configuration=Release

  test:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Build application
        run: msbuild ./Kiandra_FA2_SLD521_ComicBookStore.sln /p:Configuration=Release

      - name: Run tests
        run: echo "Running tests..."
          # Add the command to run tests (e.g., MSTest, NUnit, xUnit)

  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0

      - name: Build application
        run: msbuild ./Kiandra_FA2_SLD521_ComicBookStore.sln /p:Configuration=Release

      - name: Deploy to staging
        run: echo "Deploying to staging..."

# You can add more jobs here for additional stages (e.g., production deployment)









